Develop
AndreasAmMueller/Modbus pull request #16
Opened 2021-04-15 19:29 UTC by Luke092

Hi Andreas,
as mentioned in my comment for the issue #15 this is our solution to the multi-registry data endianness.
Also we added a "lenght" parameter in the string method to allow zero-padded string writing.

2021-04-26 16:49 UTC, AndreasAmMueller commented
Hi There,

I was thinking of another approach. Would you please try that version?

If you need a NuGet feed, you could use my developer feed: https://nuget.am-wd.de/v3/index.json

You should now be able to switch the complete behaviour within the client...

```cs
client.IsLittleEndianRemote = true;
```

2021-04-28 06:41 UTC, AndreasAmMueller commented
> 
> 
> Hi There,
> 
> I was thinking of another approach. Would you please try that version?
> 
> If you need a NuGet feed, you could use my developer feed: https://nuget.am-wd.de/v3/index.json
> 
> You should now be able to switch the complete behaviour within the client...
> 
> ```cs
> client.IsLittleEndianRemote = true;
> ```

Okay, I see the difference... I'll make a better code review - should be soon to be merged.

2021-04-28 07:37 UTC, AndreasAmMueller requested changes
I think with that renaming it would be a good solution - please review and commit to your pull request so I can merge it then ;-)

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

That name is easier to understand what happens with this flag.

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static uint GetUInt32(this IEnumerable<ModbusObject> list, int startIndex = 0, bool bigEndianRegistryOrder = true)
```suggestion
		public static uint GetUInt32(this IEnumerable<ModbusObject> list, int startIndex = 0, bool inverseRegisters = false)

```

It also takes credits of a good code style to use default values whereever possible.

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (!bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

... so it's easier to understand that an action takes place when a parameter is actually set.

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="bigEndianRegistryOrder">Change the order of WORDs in multi-registry data. True indicates Big Endian encoding, False Little Endian encoding. Default: True</param>
```suggestion
		/// <param name="inverseRegisters">Inverses the register order as required by some implementations. Default: false.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		/// <param name="lenght">The zero-padded string lenght. If 0 the string will occupy the number of bytes equals to the actual lenght of the string.</param>
```suggestion
		/// <param name="length">The zero-padded string length. If 0 (zero) the string will occupy the number of bytes equals to the actual lenght of the string.</param>

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static ModbusObject[] ToModbusRegister(this string str, ushort address, Encoding encoding = null, bool flipBytes = false, int lenght = 0)
```suggestion
		public static ModbusObject[] ToModbusRegister(this string str, ushort address, Encoding encoding = null, bool flipBytes = false, int length = 0)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +
```suggestion
			if (length > 0)
				Array.Resize(ref bytes, length);

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static ulong GetUInt64(this IEnumerable<ModbusObject> list, int startIndex = 0, bool bigEndianRegistryOrder = true)
```suggestion
		public static ulong GetUInt64(this IEnumerable<ModbusObject> list, int startIndex = 0, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (!bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static int GetInt32(this IEnumerable<ModbusObject> list, int startIndex = 0, bool bigEndianRegistryOrder = true)
```suggestion
		public static int GetInt32(this IEnumerable<ModbusObject> list, int startIndex = 0, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (!bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static long GetInt64(this IEnumerable<ModbusObject> list, int startIndex = 0, bool bigEndianRegistryOrder = true)
```suggestion
		public static long GetInt64(this IEnumerable<ModbusObject> list, int startIndex = 0, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (!bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static float GetSingle(this IEnumerable<ModbusObject> list, int startIndex = 0, bool bigEndianRegistryOrder = true)
```suggestion
		public static float GetSingle(this IEnumerable<ModbusObject> list, int startIndex = 0, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (!bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static double GetDouble(this IEnumerable<ModbusObject> list, int startIndex = 0, bool bigEndianRegistryOrder = true)
```suggestion
		public static double GetDouble(this IEnumerable<ModbusObject> list, int startIndex = 0, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (!bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static ModbusObject[] ToModbusRegister(this uint value, ushort address, bool bigEndianRegistryOrder = true)
```suggestion
		public static ModbusObject[] ToModbusRegister(this uint value, ushort address, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				for (int i = 0; i < registers.Length; i++)
```suggestion
				int startAddress = address + registers.Length - 1;
				for (int i = 0; i < registers.Length; i++)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static ModbusObject[] ToModbusRegister(this ulong value, ushort address, bool bigEndianRegistryOrder = true)
```suggestion
		public static ModbusObject[] ToModbusRegister(this ulong value, ushort address, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				for (int i = 0; i < registers.Length; i++)
```suggestion
				int startAddress = address + registers.Length - 1;
				for (int i = 0; i < registers.Length; i++)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				}
```suggestion
					registers[i] = new ModbusObject
					{
						Address = (ushort)(startAddress - i),
						Type = ModbusObjectType.HoldingRegister,
						HiByte = bytes[i * 2],
						LoByte = bytes[i * 2 + 1]
					};
				}
			}
			else
			{
				for (int i = 0; i < registers.Length; i++)
				{
					registers[i] = new ModbusObject
					{
						Address = (ushort)(address + i),
						Type = ModbusObjectType.HoldingRegister,
						HiByte = bytes[i * 2],
						LoByte = bytes[i * 2 + 1]
					};
				}

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				}
```suggestion
					registers[i] = new ModbusObject
					{
						Address = (ushort)(startAddress - i),
						Type = ModbusObjectType.HoldingRegister,
						HiByte = bytes[i * 2],
						LoByte = bytes[i * 2 + 1]
					};
				}
			}
			else
			{
				for (int i = 0; i < registers.Length; i++)
				{
					registers[i] = new ModbusObject
					{
						Address = (ushort)(address + i),
						Type = ModbusObjectType.HoldingRegister,
						HiByte = bytes[i * 2],
						LoByte = bytes[i * 2 + 1]
					};
				}

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static ModbusObject[] ToModbusRegister(this int value, ushort address, bool bigEndianRegistryOrder = true)
```suggestion
		public static ModbusObject[] ToModbusRegister(this int value, ushort address, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				for (int i = 0; i < registers.Length; i++)
```suggestion
				int startAddress = address + registers.Length - 1;
				for (int i = 0; i < registers.Length; i++)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				}
```suggestion
					registers[i] = new ModbusObject
					{
						Address = (ushort)(startAddress - i),
						Type = ModbusObjectType.HoldingRegister,
						HiByte = bytes[i * 2],
						LoByte = bytes[i * 2 + 1]
					};
				}
			}
			else
			{
				for (int i = 0; i < registers.Length; i++)
				{
					registers[i] = new ModbusObject
					{
						Address = (ushort)(address + i),
						Type = ModbusObjectType.HoldingRegister,
						HiByte = bytes[i * 2],
						LoByte = bytes[i * 2 + 1]
					};
				}

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static ModbusObject[] ToModbusRegister(this long value, ushort address, bool bigEndianRegistryOrder = true)
```suggestion
		public static ModbusObject[] ToModbusRegister(this long value, ushort address, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				for (int i = 0; i < registers.Length; i++)
```suggestion
				int startAddress = address + registers.Length - 1;
				for (int i = 0; i < registers.Length; i++)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				}
```suggestion
					registers[i] = new ModbusObject
					{
						Address = (ushort)(startAddress - i),
						Type = ModbusObjectType.HoldingRegister,
						HiByte = bytes[i * 2],
						LoByte = bytes[i * 2 + 1]
					};
				}
			}
			else
			{
				for (int i = 0; i < registers.Length; i++)
				{
					registers[i] = new ModbusObject
					{
						Address = (ushort)(address + i),
						Type = ModbusObjectType.HoldingRegister,
						HiByte = bytes[i * 2],
						LoByte = bytes[i * 2 + 1]
					};
				}

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static ModbusObject[] ToModbusRegister(this float value, ushort address, bool bigEndianRegistryOrder = true)
```suggestion
		public static ModbusObject[] ToModbusRegister(this float value, ushort address, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				for (int i = 0; i < registers.Length; i++)
```suggestion
				int startAddress = address + registers.Length - 1;
				for (int i = 0; i < registers.Length; i++)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +		public static ModbusObject[] ToModbusRegister(this double value, ushort address, bool bigEndianRegistryOrder = true)
```suggestion
		public static ModbusObject[] ToModbusRegister(this double value, ushort address, bool inverseRegisters = false)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +			if (bigEndianRegistryOrder)
```suggestion
			if (inverseRegisters)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				for (int i = 0; i < registers.Length; i++)
```suggestion
				int startAddress = address + registers.Length - 1;
				for (int i = 0; i < registers.Length; i++)

```

2021-04-28 07:37 UTC, AndreasAmMueller commented on src/Modbus.Common/Util/Extensions.cs
> +				}
```suggestion
					registers[i] = new ModbusObject
					{
						Address = (ushort)(startAddress - i),
						Type = ModbusObjectType.HoldingRegister,
						HiByte = bytes[i * 2],
						LoByte = bytes[i * 2 + 1]
					};
				}
			}
			else
			{
				for (int i = 0; i < registers.Length; i++)
				{
					registers[i] = new ModbusObject
					{
						Address = (ushort)(address + i),
						Type = ModbusObjectType.HoldingRegister,
						HiByte = bytes[i * 2],
						LoByte = bytes[i * 2 + 1]
					};
				}

```

2021-04-29 07:11 UTC, Luke092 commented
Hi Andreas,
I merged your suggestions and fix the registers creation logic.
Please check if everything is ok now.

Thanks.
Luca

2021-04-29 22:25 UTC, merged